### ISSUE TITLE
Default icon of configure

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekochat#15]
Nameなどを変えてもアイコンのDefaultが即時更新されない

**Comment by ukatama** [comment]
ほとんど仕様
必要な機能でしょうか？

**Comment by MirrgieRiana** [comment]
キャラシートURLを変更すると名前は即時反応するのにデフォルトアイコンが変わらないと、多少違和感を感じます

**Comment by ukatama** [comment]
Merge into #26
