### ISSUE TITLE
Add buttons to open static view into room list

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekochat#17]
チャットルーム選択画面から直接Static Viewに飛べるボタンが欲しい

**Comment by ukatama** [comment]
https://design.google.com/icons/ に適切なアイコンはあるでしょうか

**Comment by MirrgieRiana** [comment]
toc https://design.google.com/icons/#ic_toc
とかどうでしょう

**Comment by ukatama** [comment]
それを含めて
list
view list
toc
reorder
view_headline
あたりが候補でしょうか
意味的にはlistが近いかもしれない

そもそもアイコンをやめて文字で示すという手もあります

**Comment by MirrgieRiana** [comment]
この先ここにどんな機能が増える（アイコンを変える羽目になる）かは分からないので、
現状はどれでもいいのではないでしょうか
