### ISSUE TITLE
Hidden radio buttons

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekochat#18]
Name and Icon画面で、アップロードしたファイルの名前が長いと選択時のラジオボタンが隠れる問題

いっそラジオボタンを隠してしまうか、ファイル名をポップアップヒントにするのはどうか

**Comment by ukatama** [comment]
本来はファイル名が隠れる仕様
スタイルがバグっていますが

**Comment by ukatama** [comment]
Chromeのみのバグ
