### ISSUE TITLE
Dice enhancement

### ISSUE THREAD

**Issue by ukatama** [ukatama/nekochat#22]
古臭いダイスボットを置き換える

**Comment by MirrgieRiana** [comment]
全体的な方針

- 単純でない数式を処理可能
- 多数のキャラクターに対する処理を出来るだけ少ない記述で処理可能
- いくつかの具体的で利用頻度の高いユースケースに対して、手短で可読性の高い構文を与える
  - 利用するだけなら動作原理を知る必要がないように
- それでいて特定のユースケースに特化せず、全体として一貫性のある文法を持つ
  - 高度な利用者はより独創性の高い処理ができるように

**Comment by ukatama** [comment]
:+1:

**Comment by MirrgieRiana** [comment]
link
https://github.com/MirrgieRiana/scriptFluorite5
