### ISSUE TITLE
 Performance issues

### ISSUE THREAD

**Issue by ukatama** [ukatama/nekochat#32]
Too heavy ?
- on old messages loaded
- on input previews added

@MirrgieRiana 調査お願い

**Comment by MirrgieRiana** [comment]
## 部屋一覧へのページ遷移の重さの検証

### 方法

- 一旦URL指定で部屋一覧のページを表示した後、ルームに入り、Leaveで部屋一覧に戻り、再度同じルームに入る
- その状態でパフォーマンス解析を開始し、ブラウザの機能で戻るを2回行ったあと結果を終了

### 結果

- グラフ上で前にある負荷：　部屋一覧への遷移
- グラフ上で後にある負荷：　チャットルームへの遷移
- OS：　Windows7 x64
- 上の画像：　Chrome 48.0.2564.109 m (64-bit)
- 下の画像：　Firefox 44.0.2

![2016-02-17 22_17_34](https://cloud.githubusercontent.com/assets/15280246/13110581/510b89d4-d5c4-11e5-9926-938f5b9d0083.png)
![2016-02-17 19_57_29](https://cloud.githubusercontent.com/assets/15280246/13110544/163ac3d8-d5c4-11e5-95de-bf0417c9de6d.png)

### その他

- 戻る・リンク・URL指定・ページの更新などで部屋一覧を表示するときに硬直が発生
  - Chrome・Firefoxで発生
  - 硬直中はスクロールなどに反応しない
  - 時間はFirefoxでは10秒程度、Chromeでは5秒程度
  - チャットルームからの戻る・リンクでの遷移では、硬直の間部屋一覧ではなくチャットルームが表示されている
    - この後表示される部屋一覧画面では、一覧が既に埋まった状態で表示される
  - ページの更新やURL指定で来た時は部屋一覧画面で硬直する
    - 固まっている間は一覧が空か不完全に埋まった状態で表示される
- 部屋一覧からチャットルームに戻る際にたまに遅延が発生
  - Chromeで発生し、Firefoxでは発生せず
  - こちらは発生しないときの方が多い
  - 遅延中はスクロールなどを受け付ける
  - 時間は10秒程度
  - 遅延中は部屋一覧の画面が表示されている

**Comment by MirrgieRiana** [comment]
## 過去メッセージの受信時の硬直

### 結果

![2016-02-17 23_08_50](https://cloud.githubusercontent.com/assets/15280246/13111922/e149c8b0-d5cb-11e5-9cd7-cd392eb4f888.png)
![2016-02-17 23_11_10](https://cloud.githubusercontent.com/assets/15280246/13111925/e3a193b8-d5cb-11e5-8b27-9004e6ca9ac6.png)

**Comment by MirrgieRiana** [comment]
## 入力プレビューの重さの検証

### 方法

- 同じルームを別ウィンドウで2個開く
- 片方はパフォーマンス解析状態にしておく
- もう片方でチャットの入力欄をフォーカスし、IME/OFFで`a`と入力。その後BackSpaceで除去

### 結果

Chrome

![2016-02-17 23_19_45](https://cloud.githubusercontent.com/assets/15280246/13112279/788246c0-d5cd-11e5-9aff-6570b18b0206.png)

Firefox：　追加時

![2016-02-17 23_23_01](https://cloud.githubusercontent.com/assets/15280246/13112303/83d49b2c-d5cd-11e5-95c8-5f2562d523f1.png)

Firefox：　除去時

![2016-02-17 23_23_13](https://cloud.githubusercontent.com/assets/15280246/13112306/8670e818-d5cd-11e5-91ac-818ae4cd189e.png)

**Comment by MirrgieRiana** [comment]
## ツールチップ表示の重さの検証

### 方法

- 同じチャットルームを2つのタブで開く
- 片方をパフォーマンス計測状態にする
- もう片方のタブを閉じる
- ツールチップが消えた段階で計測を完了

### 結果

Chrome

![2016-02-17 23_19_45](https://cloud.githubusercontent.com/assets/15280246/13112502/44c6909c-d5ce-11e5-9f66-1718d9ed7c69.png)

Firefox：　追加時

![2016-02-17 23_28_57](https://cloud.githubusercontent.com/assets/15280246/13112518/565b71e2-d5ce-11e5-8e01-3fc252b3785f.png)

Firefox：　除去時

![2016-02-17 23_29_11](https://cloud.githubusercontent.com/assets/15280246/13112522/5b21a1f6-d5ce-11e5-9b17-733b427e3136.png)

### その他

- 入室時はツールチップが連続して7回ほど表示される

**Comment by MirrgieRiana** [comment]
ここまででとりあえず報告完了

**Comment by ukatama** [comment]
遅延の発生タイミング（画面遷移の前など）と遅延時間を一つにまとめて欲しいです。

遅延中に実行されている関数名及びbrowser.js中の行番号（Minifyされてないもの）もあると助かります。

**Comment by MirrgieRiana** [comment]
### 行番号調査

部屋一覧ページに遷移する際の硬直

- 1番目：　browser.js:79240
- 2番目：　browser.js:20259
- 3番目：　browser.js:20259
- ![2016-02-18 00_22_27](https://cloud.githubusercontent.com/assets/15280246/13114191/bd79d31c-d5d5-11e5-890c-0cbd07236410.png)

過去メッセージを受信する際の硬直

- 主要な遅延箇所：　browser.js:20259

入力プレビューの際の硬直

- 開始：　browser.js:20259
- 終了：　browser.js:20259

ツールチップ表示の際の硬直

- 開始
  - CSS
  - browser.js:20259
- 終了：　CSS

**Comment by ukatama** [comment]
Thank you！
対応してみます

**Comment by ukatama** [comment]
> ツールチップ表示
これは通知Snackbarを指しているようですね

Tooltipはボタンのマウスオーバーで表示されるアイテム

**Comment by ukatama** [comment]
> 遅延の発生タイミング（画面遷移の前など）と遅延時間を一つにまとめて欲しいです。

概算
- 部屋一覧
  - 10,000ms/5,000ms
- 過去ログ
  - 800ms/900ms
- 入力プレビュー
  - 400ms/650ms
- Snackbar
  - 480ms/650ms

**Comment by ukatama** [comment]
#37 increases performance of room list about 1,000ms to 500ms in my PC.

@MirrgieRiana 部屋一覧の変更とパフォーマンスの改善をしたのでそこだけ確認お願いします

**Comment by ukatama** [comment]
probably resolved
