### ISSUE TITLE
My Rooms label is too quiet in a list of rooms

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/nekochat#33]
部屋一覧のページで部屋リストを区切る「Recentry Joined Rooms」「My Rooms」といったラベルが地味で、
高速でスクロールした際に「My Rooms」ラベルを見失ってしまう

これに起因する問題の例

- チャットルームを新規作成した場合「My Rooms」リストに追加されるので、新規作成した部屋を見失う

**Comment by ukatama** [comment]
#35 で一つのリストに統合されるので解決予定
